"use client";

import { useState } from "react";
import dynamic from "next/dynamic";
import { Camera, Check, Copy, Download, MessageCircle, Share2, X } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useDeviceCapabilities } from "@/hooks/useDeviceCapabilities";
import { recordShareAction } from "@/lib/actions/share.actions";
import type { PhotoCardData } from "./PhotoCardComposer";

const PhotoCardComposer = dynamic(
  () => import("./PhotoCardComposer").then((m) => ({ default: m.PhotoCardComposer })),
  { ssr: false }
);

export type ShareCardType = "match" | "player" | "ranking" | "league" | "badge";

interface ShareModalProps {
  open: boolean;
  onClose: () => void;
  /** Public share URL (e.g. /share/match/{id}) */
  shareUrl: string;
  /** Pre-composed WhatsApp text */
  whatsappText: string;
  /** URL of the OG image generated by /api/og/* */
  ogImageUrl: string;
  /** Filename for download (without extension) */
  downloadName?: string;
  /** Match ID for share tracking (optional — only for match shares) */
  matchId?: string;
  /** Data for PhotoCardComposer (only player/match types supported) */
  cardData?: PhotoCardData;
}

export function ShareModal({
  open,
  onClose,
  shareUrl,
  whatsappText,
  ogImageUrl,
  downloadName = "pasala-card",
  matchId,
  cardData,
}: ShareModalProps) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [photoComposerOpen, setPhotoComposerOpen] = useState(false);
  const { toast } = useToast();
  const { showPhotoComposer } = useDeviceCapabilities();

  if (!open) return null;

  if (photoComposerOpen && cardData) {
    return <PhotoCardComposer cardData={cardData} onClose={() => setPhotoComposerOpen(false)} />;
  }

  // Use a relative path for the img preview and download fetch so it always
  // hits the current server (avoids cross-origin issues when NEXT_PUBLIC_SITE_URL
  // points to production while running locally).
  const ogImageRelative = (() => {
    try {
      const u = new URL(ogImageUrl);
      return u.pathname + u.search;
    } catch {
      return ogImageUrl; // already relative
    }
  })();

  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(whatsappText)}`;

  function trackShare(channel: "whatsapp" | "copylink" | "webshare") {
    if (matchId) recordShareAction(matchId, channel).catch(() => {});
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(shareUrl);
      trackShare("copylink");
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
      toast({ title: "¡Link copiado!", description: "Pegalo donde quieras compartirlo." });
    } catch {
      toast({ title: "Error", description: "No se pudo copiar el link.", variant: "destructive" });
    }
  }

  async function handleDownload() {
    setDownloading(true);
    try {
      const res = await fetch(ogImageRelative);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${downloadName}.png`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast({ title: "Error", description: "No se pudo descargar la imagen.", variant: "destructive" });
    } finally {
      setDownloading(false);
    }
  }

  async function handleWebShare() {
    if (typeof navigator?.share !== "function") return;
    try {
      await navigator.share({ text: whatsappText, url: shareUrl });
      trackShare("webshare");
    } catch {
      // user cancelled – no error
    }
  }

  const canWebShare = typeof navigator !== "undefined" && typeof navigator.share === "function";

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="fixed inset-x-4 bottom-4 z-50 mx-auto max-w-md rounded-[28px] border border-white/10 bg-slate-950 p-6 shadow-2xl sm:inset-x-auto sm:left-1/2 sm:-translate-x-1/2 sm:bottom-8">
        {/* Header */}
        <div className="mb-5 flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-400">Compartir</p>
            <h3 className="mt-0.5 text-lg font-black text-white">Tu card de PASALA</h3>
          </div>
          <button
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-white/60 hover:bg-white/20 transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Image preview */}
        <div className="mb-5 overflow-hidden rounded-2xl border border-white/10 bg-slate-900">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={ogImageRelative}
            alt="Card preview"
            className="w-full object-cover"
            style={{ aspectRatio: "1200/630" }}
          />
        </div>

        {/* Actions */}
        <div className="space-y-2">
          {/* Photo composer — mobile only, if cardData is provided */}
          {showPhotoComposer && cardData && (
            <button
              onClick={() => setPhotoComposerOpen(true)}
              className="flex w-full items-center justify-center gap-2.5 rounded-2xl border border-white/10 bg-white/8 py-3.5 text-sm font-black uppercase tracking-widest text-white/90 transition-all hover:bg-white/15 active:scale-[0.98]"
            >
              <Camera className="h-4 w-4" />
              Personalizar con tu foto
            </button>
          )}

          {/* WhatsApp */}
          <a
            href={whatsappUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => trackShare("whatsapp")}
            className="flex w-full items-center justify-center gap-2.5 rounded-2xl bg-[#25D366] py-3.5 text-sm font-black uppercase tracking-widest text-white transition-all hover:bg-[#128C7E] active:scale-[0.98]"
          >
            <MessageCircle className="h-4 w-4 fill-current" />
            Compartir por WhatsApp
          </a>

          {/* Secondary row */}
          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-2.5 text-xs font-bold text-white/80 transition-colors hover:bg-white/10"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copiado" : "Copiar link"}
            </button>

            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-2.5 text-xs font-bold text-white/80 transition-colors hover:bg-white/10 disabled:opacity-50"
            >
              <Download className="h-3.5 w-3.5" />
              {downloading ? "Descargando..." : "Descargar imagen"}
            </button>
          </div>

          {/* Web Share (mobile only, progressive enhancement) */}
          {canWebShare && (
            <button
              onClick={handleWebShare}
              className="flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-2.5 text-xs font-bold text-white/60 transition-colors hover:bg-white/10"
            >
              <Share2 className="h-3.5 w-3.5" />
              Más opciones de compartir
            </button>
          )}
        </div>
      </div>
    </>
  );
}
